import {
  gintama,
  steins,
  deathnote,
  higurashi,
  monster,
  geass,
  eighty,
  summer,
  nhk,
  jujutsu,
  titan,
  demon,
  another,
  parasyte,
  rainbow,
  neverland,
  zom,
  mob,
  beck,
  bakuman,
  spy,
  chainsaw,
  punch,
} from "../../src/assets/animes";

const portalAnimes = [
  // Left
  {
    position: [0.25, 0, 1.5],
    rotation: [0, 0, 0],
    src: gintama,
    title: "Gintama",
    url: "https://www.youtube.com/watch?v=H9Ccf31L_mI",
    hasStar: true,
  },
  {
    position: [-2.5, 0, 0],
    rotation: [0, 0, 0],
    src: steins,
    title: "Steins Gate",
    url: "https://www.youtube.com/watch?v=uMYhjVwp0Fk",
    hasStar: true,
  },
  {
    position: [-3.6, 0, 1.5],
    rotation: [0, 0, 0],
    src: deathnote,
    title: "Death Note",
    url: "https://www.youtube.com/watch?v=NlJZ-YgAt-c",
  },
  {
    position: [-1.15, 0, 1],
    rotation: [0.15, -0.5, 0],
    src: higurashi,
    title: "Higurashi When They Cry",
    url: "https://www.youtube.com/watch?v=JNAedxl7hhA",
    hasStar: true,
  },
  {
    position: [-3.65, 0, 0],
    rotation: [-0.15, Math.PI / 2, 0],
    src: monster,
    title: "Monster",
    url: "https://www.youtube.com/watch?v=9aXTKhnockM",
  },

  // Center
  {
    position: [2.5, 0, -5],
    rotation: [0, 0, 0],
    src: geass,
    title: "Code Geass",
    url: "https://www.youtube.com/watch?v=ulQGo6X7kFo",
  },
  {
    position: [0.75, 0, -7],
    rotation: [-0.15, Math.PI / 2, 0],
    src: eighty,
    title: "86",
    url: "https://www.youtube.com/watch?v=Mb5ESlC3FNc",
  },
  {
    position: [-0.5, 0, -7.5],
    rotation: [0, 0, 0],
    src: summer,
    title: "Summer Time Rendering",
    url: "https://www.youtube.com/watch?v=8Eg-BaDX85s",
  },
  {
    position: [4.5, 0, -7],
    rotation: [0.15, -0.5, 0],
    src: nhk,
    title: "Welcome to NHK",
    url: "https://www.youtube.com/watch?v=9p5qSLNPQCk",
  },
  {
    position: [6, 0, -7.5],
    rotation: [0, 0, 0],
    src: titan,
    title: "Attack on Titans",
    url: "https://www.youtube.com/watch?v=MGRm4IzK1SQ",
  },
  {
    position: [-2.25, 0, -8.5],
    rotation: [-0.5, 0, 0],
    src: another,
    title: "Another",
    url: "https://www.youtube.com/watch?v=_U_57mzfjB4",
  },
  {
    position: [-4.15, 0, -10],
    rotation: [0, 0, 0],
    src: neverland,
    title: "The Promised Neverland",
    url: "https://www.youtube.com/watch?v=ApLudqucq-s",
  },

  // Right
  {
    position: [7, 0, -5],
    rotation: [0, -Math.PI / 2, 0],
    src: jujutsu,
    title: "Jujutsu Kaisen",
    url: "https://www.youtube.com/watch?v=Pm-wNmS9RGI",
  },
  {
    position: [10, 0, -3],
    rotation: [0, -Math.PI / 2, 0],
    src: chainsaw,
    title: "Chainsaw Man",
    url: "https://www.youtube.com/watch?v=v4yLeNt-kCU",
  },
  {
    position: [19, 0, 3],
    rotation: [0, -Math.PI / 2, 0],
    src: punch,
    title: "One Punch Man",
    url: "https://www.youtube.com/watch?v=78ngg0SRlEI",
  },
  {
    position: [10, 0, -7],
    rotation: [0, -Math.PI / 2, 0],
    src: demon,
    title: "Demon Slayer",
    url: "https://www.youtube.com/watch?v=VQGCKyvzIM4",
  },
  {
    position: [14, 0, -10],
    rotation: [0, -Math.PI / 2, 0],
    src: mob,
    title: "Mob Psycho",
    url: "https://www.youtube.com/watch?v=nTze7vAdRpM",
  },

  // Back
  {
    position: [-5.75, 0, -12],
    rotation: [-0.5, 0, 0],
    src: beck,
    title: "Beck",
    url: "https://www.youtube.com/watch?v=GNgReTHy1EA",
  },
  {
    position: [-7.75, 0, -14],
    rotation: [0, 0, 0],
    src: rainbow,
    title: "Rainbow",
    url: "https://www.youtube.com/watch?v=ibkhGFKhyW8",
  },
  {
    position: [-10.25, 0, -16],
    rotation: [-0.5, 0, 0],
    src: parasyte,
    title: "Parasyte",
    url: "https://www.youtube.com/watch?v=dT1TA-KANac",
  },
  {
    position: [-2.5, 0, -12],
    rotation: [-0.5, 0, 0],
    src: spy,
    title: "Spy Family",
    url: "https://www.youtube.com/watch?v=Oqd2C3oZkBU",
  },
  {
    position: [-0.5, 0, -14],
    rotation: [0, 0, 0],
    src: zom,
    title: "Zom100",
    url: "https://www.youtube.com/watch?v=68LwDMvPCgM",
  },
  {
    position: [2.15, 0, -16],
    rotation: [-0.5, 0, 0],
    src: bakuman,
    title: "Bakuman",
    url: "https://www.youtube.com/watch?v=KB7QDax8PtY",
  },
];

export default portalAnimes;
