import {
  breaking,
  saul,
  mouse,
  flower,
  prison,
  kingdom,
  alchemy,
  waikiki,
  mother,
  vagabond,
  saints,
  name,
  friends,
  reply,
  luna,
  dead,
  happiness,
  doona,
  zombie,
  diary,
  vincenzo,
  castaway,
} from "../../src/assets/dramas";

const portalDramas = [
  // Center
  {
    position: [0, 0, 1.5],
    rotation: [0, 0, 0],
    src: saul,
    title: "Better Call Saul",
    url: "https://www.youtube.com/watch?v=HN4oydykJFc",
    hasStar: true,
  },
  {
    position: [-1, 0, 0],
    rotation: [0, 0, 0],
    src: breaking,
    title: "Breaking Bad",
    url: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    hasStar: true,
  },
  {
    position: [-2, 0, -1],
    rotation: [-0.5, 0, 0],
    src: kingdom,
    title: "Kingdom",
    url: "https://www.youtube.com/watch?v=4l-yByZpaaM",
  },
  {
    position: [1, 0, 0],
    rotation: [0, 0, 0],
    src: mouse,
    title: "Mouse",
    url: "https://www.youtube.com/watch?v=i_K9U3gE9os",
    hasStar: true,
  },
  {
    position: [2, 0, -1],
    rotation: [-0.5, 0, 0],
    src: flower,
    title: "Flower of Evil",
    url: "https://www.youtube.com/watch?v=oE5qyfKgYFE",
  },

  // Left
  {
    position: [-4.5, 0, -3],
    rotation: [0, Math.PI / 4, 0],
    src: mother,
    title: "The Good Bad Mother",
    url: "https://www.youtube.com/watch?v=CzVi_hIZ3mc",
  },
  {
    position: [-7, 0, -3.5],
    rotation: [0, Math.PI / 4, 0],
    src: name,
    title: "My Name",
    url: "https://www.youtube.com/watch?v=ZOl7iOrD31Q",
  },
  {
    position: [-11, 0, -4],
    rotation: [0, Math.PI / 4, 0],
    src: saints,
    title: "Narco-Saints",
    url: "https://www.youtube.com/watch?v=1MTIrScpSPU",
  },
  {
    position: [-4.5, 0, -4.5],
    rotation: [0, Math.PI / 4, 0],
    src: happiness,
    title: "Happiness",
    url: "https://www.youtube.com/watch?v=uaHq2ImPrHs",
  },
  {
    position: [-4.75, 0, -8.5],
    rotation: [0, Math.PI / 4, 0],
    src: dead,
    title: "All of Us Are Dead",
    url: "https://www.youtube.com/watch?v=IN5TD4VRcSM",
  },

  // Right
  {
    position: [4.5, 0, -3],
    rotation: [0, -Math.PI / 4, 0],
    src: alchemy,
    title: "Alchemy of Souls",
    url: "https://www.youtube.com/watch?v=nlRw1CGbFU0",
  },
  {
    position: [7.5, 0, -3.5],
    rotation: [0, -Math.PI / 4, 0],
    src: luna,
    title: "Hotel del Luna",
    url: "https://www.youtube.com/watch?v=1IjMTR2DxlA",
  },
  {
    position: [12, 0, -4],
    rotation: [0, -Math.PI / 4, 0],
    src: vincenzo,
    title: "Vincenzo",
    url: "https://www.youtube.com/watch?v=_J8tYxYB_YU",
  },
  {
    position: [4.5, 0, -4.5],
    rotation: [0, -Math.PI / 4, 0],
    src: doona,
    title: "Doona",
    url: "https://www.youtube.com/watch?v=v4rtx48siJI",
  },
  {
    position: [4.75, 0, -8.5],
    rotation: [0, -Math.PI / 4, 0],
    src: vagabond,
    title: "Vagabond",
    url: "https://www.youtube.com/watch?v=PndjeodkGj8",
  },

  // Back
  {
    position: [3.75, 0, -15.5],
    rotation: [0, Math.PI / 8, 0],
    src: castaway,
    title: "Castaway Diva",
    url: "https://www.youtube.com/watch?v=Qieu0vtPaKc",
  },
  {
    position: [4.5, 0, -17.5],
    rotation: [0, Math.PI / 8, 0],
    src: reply,
    title: "Reply 1988",
    url: "https://www.youtube.com/watch?v=c-EMf3JdxUA",
  },
  {
    position: [5.5, 0, -19.5],
    rotation: [0, Math.PI / 8, 0],
    src: friends,
    title: "Friends",
    url: "https://www.youtube.com/watch?v=H29XSxoKp80",
  },
  {
    position: [7, 0, -22.5],
    rotation: [0, Math.PI / 8, 0],
    src: prison,
    title: "Prison Playbook",
    url: "https://www.youtube.com/watch?v=cxRhBctpD3E",
  },
  {
    position: [2, 0, -16.5],
    rotation: [0, Math.PI / 8, 0],
    src: waikiki,
    title: "Welcome to Waikiki",
    url: "https://www.youtube.com/watch?v=AJ_eVJp-IuQ",
  },
  {
    position: [-1.75, 0, -18.5],
    rotation: [0, Math.PI / 8, 0],
    src: zombie,
    title: "Zombie Detective",
    url: "https://www.youtube.com/watch?v=t2H85VxhZ6o",
  },
  {
    position: [-6, 0, -20.5],
    rotation: [0, Math.PI / 8, 0],
    src: diary,
    title: "Psychopath Diary",
    url: "https://www.youtube.com/watch?v=UDOMl0EACx0",
  },
];

export default portalDramas;
