import {
  iu,
  leehi,
  taeyeon,
  bol4,
  stimson,
  barrera,
  misch,
  mayer,
  sun,
  rini,
  major,
  fkj,
  kang,
  bernat,
  eve,
  yoasobi,
  aimyon,
  dandism,
  lisa,
  tricot,
  supercell,
  alt,
  ben,
  blg,
  incubus,
  mcr,
  paramore,
  dua,
  pomeranz,
  rankin,
} from "../../src/assets/music";

const portalMusic = [
  // Front Left
  {
    position: [-1, 0, 1.5],
    rotation: [0, Math.PI / 8.5, 0],
    src: iu,
    title: "IU",
    url: "https://www.youtube.com/watch?v=d9IxdwEFk1c",
    hasStar: true,
  },
  {
    position: [-2, 0, 2.5],
    rotation: [0, Math.PI / 8.5, 0],
    src: leehi,
    title: "Lee Hi",
    url: "https://www.youtube.com/watch?v=ZFdHh-MWB6Q",
    hasStar: true,
  },
  {
    position: [-0.5, 0, -1.5],
    rotation: [0, Math.PI / 8.5, 0],
    src: taeyeon,
    title: "Taeyeon",
    url: "https://www.youtube.com/watch?v=lHEOj3d7YS4",
  },
  {
    position: [-3.5, 0, -2.5],
    rotation: [0, Math.PI / 8.5, 0],
    src: bol4,
    title: "BOL4",
    url: "https://www.youtube.com/watch?v=y5MAgMVwfFs",
  },

  // Back Center
  {
    position: [5, 0, -13],
    rotation: [0, -Math.PI / 9, 0],
    src: eve,
    title: "Eve",
    url: "https://www.youtube.com/watch?v=O8IhTEi3U9U",
  },
  {
    position: [3.5, 0, -15],
    rotation: [0, Math.PI / 9, 0],
    src: yoasobi,
    title: "Yoasobi",
    url: "https://www.youtube.com/watch?v=8iuLXODzL04",
  },
  {
    position: [7.5, 0, -15],
    rotation: [0, Math.PI / -9, 0],
    src: aimyon,
    title: "Aimyon",
    url: "https://www.youtube.com/watch?v=jO8aO5y2Q9g",
  },
  {
    position: [8.5, 0, -13.5],
    rotation: [0, Math.PI / -16, 0],
    src: dandism,
    title: "Official Hige Dandism",
    url: "https://www.youtube.com/watch?v=oLrp9uTa9gw",
  },
  {
    position: [5.75, 0, -21],
    rotation: [0, 0, 0],
    src: lisa,
    title: "Lisa",
    url: "https://www.youtube.com/watch?v=CwkzK-F0Y00",
  },
  {
    position: [3, 0, -25],
    rotation: [0, Math.PI / 16, 0],
    src: tricot,
    title: "Tricot",
    url: "https://www.youtube.com/watch?v=-rZWdolJfgk",
  },
  {
    position: [9.5, 0, -24],
    rotation: [0, Math.PI / 16, 0],
    src: supercell,
    title: "Supercell",
    url: "https://www.youtube.com/watch?v=FM1iXQpRLgQ",
  },

  // Back Right
  {
    position: [15, 0, -8.5],
    rotation: [0, -Math.PI / 2.5, 0],
    src: stimson,
    title: "Johnny Stimson",
    url: "https://www.youtube.com/watch?v=Y9faB5tXij0",
  },
  {
    position: [10, 0, -8],
    rotation: [0, -Math.PI / 2.5, 0],
    src: barrera,
    title: "Jesse Barrera",
    url: "https://www.youtube.com/watch?v=zr3lA3zAhQ8",
  },
  {
    position: [16, 0, -15],
    rotation: [0, -Math.PI / 2.5, 0],
    src: misch,
    title: "Tom Misch",
    url: "https://www.youtube.com/watch?v=EXWOJvlDwbU",
  },
  {
    position: [22, 0, -18],
    rotation: [0, -Math.PI / 2.5, 0],
    src: rini,
    title: "Rini",
    url: "https://www.youtube.com/watch?v=oNIBAL8x9-4",
  },
  {
    position: [22, 0, -25],
    rotation: [0, -Math.PI / 2.5, 0],
    src: mayer,
    title: "John Mayer",
    url: "https://www.youtube.com/watch?v=yT8SYItNvKg",
  },
  {
    position: [20, 0, -21],
    rotation: [0, -Math.PI / 2.5, 0],
    src: bernat,
    title: "Jeff Bernat",
    url: "https://www.youtube.com/watch?v=_MlYUgZnZcU",
    hasStar: true,
  },
  {
    position: [24, 0, -18],
    rotation: [0, -Math.PI / 4, 0],
    src: major,
    title: "Bruno Major",
    url: "https://www.youtube.com/watch?v=sRJ4RywOPvA",
  },
  {
    position: [23, 0, -24],
    rotation: [0, -Math.PI / 2.5, 0],
    src: kang,
    title: "Sarah Kang",
    url: "https://www.youtube.com/watch?v=m8g6exedStI",
  },
  {
    position: [20, 0, -13],
    rotation: [0, -Math.PI / 2.5, 0],
    src: sun,
    title: "Sun Rai",
    url: "https://www.youtube.com/watch?v=9zEl-FQLI4A",
  },
  {
    position: [22, 0, -12],
    rotation: [0, -Math.PI / 2.5, 0],
    src: fkj,
    title: "FKJ",
    url: "https://www.youtube.com/watch?v=hC8CH0Z3L54",
  },

  //Back Left
  {
    position: [-15, 0, -7],
    rotation: [0, Math.PI / 5, 0],
    src: dua,
    title: "Dua Lipa",
    url: "https://www.youtube.com/watch?v=Nj2U6rhnucI",
  },
  {
    position: [-15, 0, -10],
    rotation: [0, Math.PI / 5, 0],
    src: ben,
    title: "Breaking Benjamin",
    url: "https://www.youtube.com/watch?v=x9hZFyoqp7Q",
  },
  {
    position: [-24, 0, -15],
    rotation: [0, Math.PI / 5, 0],
    src: incubus,
    title: "Incubus",
    url: "https://www.youtube.com/watch?v=kMS-xy4eJMU",
  },
  {
    position: [-25, 0, -11],
    rotation: [0, Math.PI / 5, 0],
    src: alt,
    title: "All Time Low",
    url: "https://www.youtube.com/watch?v=YYoJY79obwA",
  },
  {
    position: [-22.5, 0, -11],
    rotation: [0, Math.PI / 5, 0],
    src: blg,
    title: "Boys Like Girls",
    url: "https://www.youtube.com/watch?v=AW3RspM7v9M",
  },
  {
    position: [-21, 0, -12],
    rotation: [0, Math.PI / 5, 0],
    src: mcr,
    title: "My Chemical Romance",
    url: "https://www.youtube.com/watch?v=x7g1ppGE1Xs",
  },
  {
    position: [-19, 0, -12],
    rotation: [0, Math.PI / 15, 0],
    src: paramore,
    title: "Paramore",
    url: "https://www.youtube.com/watch?v=xIYJ7VaSxYY",
  },

  //Back Edge Left
  {
    position: [-25, 0, -8],
    rotation: [0, Math.PI / 5, 0],
    src: pomeranz,
    title: "David Pomeranz",
    url: "https://www.youtube.com/watch?v=WWf4ZBwVLok",
  },
  {
    position: [-28, 0, -9],
    rotation: [0, Math.PI / 5, 0],
    src: rankin,
    title: "Kenny Rankin",
    url: "https://www.youtube.com/watch?v=uODVPHZD9oo",
  },
];

export default portalMusic;
